//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScriptManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlBox
    {
        public ControlBox()
        {
            this.Sensor = new HashSet<Sensor>();
            this.SmartThing = new HashSet<SmartThing>();
            this.Scenaries = new HashSet<Scenario>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public bool IsStable { get; set; }
    
        public virtual UserGroup UserGroup { get; set; }
        public virtual ICollection<Sensor> Sensor { get; set; }
        public virtual ICollection<SmartThing> SmartThing { get; set; }
        public virtual ICollection<Scenario> Scenaries { get; set; }
    }
}
