//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScriptManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScriptModelContainer1 : DbContext
    {
        public ScriptModelContainer1()
            : base("name=ScriptModelContainer1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> AdminSet { get; set; }
        public DbSet<User> UserSet { get; set; }
        public DbSet<Scenario> ScenarioSet { get; set; }
        public DbSet<UserGroup> UserGroupSet { get; set; }
        public DbSet<SensorType> SensorTypeSet { get; set; }
        public DbSet<SmartThingType> SmartThingTypeSet { get; set; }
        public DbSet<SmartThingTypeDictionary> SmartThingTypeDictionarySet { get; set; }
        public DbSet<SmartPlace> SmartPlaceSet { get; set; }
        public DbSet<Sensor> SensorSet { get; set; }
        public DbSet<SmartThing> SmartThingSet { get; set; }
        public DbSet<ControlBox> ControlBoxSet { get; set; }
        public DbSet<LicenceDictionary> LicenceDictionarySet { get; set; }
    }
}
