//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScriptManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        public UserGroup()
        {
            this.Users = new HashSet<User>();
            this.Children = new HashSet<UserGroup>();
            this.SmartPlaces = new HashSet<SmartPlace>();
            this.ControlBoxes = new HashSet<ControlBox>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Licence Licence { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<UserGroup> Children { get; set; }
        public virtual UserGroup Parent { get; set; }
        public virtual ICollection<SmartPlace> SmartPlaces { get; set; }
        public virtual ICollection<ControlBox> ControlBoxes { get; set; }
    }
}
