//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScriptManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BoolSensor : Sensor
    {
        [Display(Name = "Значение")]
        public bool Value { get; set; }

        public void TurnOn()
        {
            Value = true;
        }
        public void TurnOff()
        {
            Value = false;
        }
    }
}
