//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScriptManager.Models
{
    using System;
    
    public enum Licence : int
    {
        None = 0,
        PersonalFree = 1,
        PersonalSimple = 2,
        CompanySimple = 3,
        PersonalMiddle = 4,
        CompanyMiddle = 5,
        PersonalFull = 6,
        CompanyFull = 7
    }
}
