//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScriptManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sensor
    {
        public long Id { get; set; }
        public string Name { get; set; }
    
        public virtual SensorType SensorType { get; set; }
        public virtual SmartPlace SmartPlace { get; set; }
        public virtual ControlBox ControlBox { get; set; }
    }
}
