//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScriptManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class SmartThing
    {


        [HiddenInput(DisplayValue = false)]
        public long Id { get; set; }

        [StringLength(50, MinimumLength = 3, ErrorMessage = "Длинна должна быть от 3 до 50 символов")]
        [Required(ErrorMessage = "Не допускает пустое значение")]
        [Display(Name = "Название")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Не допускает пустое значение")]
        [Display(Name = "Тип умной вещи")]
        public virtual SmartThingType SmartThingType { get; set; }

        [Required(ErrorMessage = "Не допускает пустое значение")]
        [Display(Name = "Контроллер")]
        public virtual ControlBox ControlBox { get; set; }


        [Display(Name = "Помещение")]
        public virtual SmartPlace SmartPlace { get; set; }
    }
}
