//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScriptManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmartPlace
    {
        public SmartPlace()
        {
            this.Sensors = new HashSet<Sensor>();
            this.SmartThings = new HashSet<SmartThing>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
    
        public virtual UserGroup UserGroup { get; set; }
        public virtual ICollection<Sensor> Sensors { get; set; }
        public virtual ICollection<SmartThing> SmartThings { get; set; }
    }
}
