//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScriptManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class SmartThingType
    {
        public SmartThingType()
        {
            this.Scenaries = new HashSet<Scenario>();
            this.SmartThings = new HashSet<SmartThing>();
        }

        [HiddenInput(DisplayValue = false)]
        public long Id { get; set; }

        [StringLength(50, MinimumLength = 3, ErrorMessage = "Длинна должна быть от 3 до 50 символов")]
        [Required(ErrorMessage = "Не допускает пустое значение")]
        [Display(Name = "Название")]
        public string Name { get; set; }
    
        public virtual ICollection<Scenario> Scenaries { get; set; }

        [Required(ErrorMessage = "Не допускает пустое значение")]
        [Display(Name = "Соответствующая запись в словаре умных вещей")]
        public virtual SmartThingTypeDictionary SmartThingTypeDictionary { get; set; }
        public virtual ICollection<SmartThing> SmartThings { get; set; }
    }
}
