//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScriptManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class UserGroup
    {
        public UserGroup()
        {
            this.Users = new HashSet<User>();
            this.Children = new HashSet<UserGroup>();
            this.SmartPlaces = new HashSet<SmartPlace>();
            this.ControlBoxes = new HashSet<ControlBox>();
        }

        [HiddenInput(DisplayValue = false)]
        public long Id { get; set; }

        [RegularExpression(@"[a-zA-Zа-яА-Я0-9 ]*", ErrorMessage = "Введены не допустимые символы")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Длинна должна быть от 3 до 50 символов")]
        [Required(ErrorMessage = "Не допускает пустое значение")]
        [Display(Name = "Название")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Не допускает пустое значение")]
        [Display(Name = "Лицензия")]
        public Licence Licence { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<UserGroup> Children { get; set; }
        public virtual UserGroup Parent { get; set; }
        public virtual ICollection<SmartPlace> SmartPlaces { get; set; }
        public virtual ICollection<ControlBox> ControlBoxes { get; set; }
    }
}
